# Generated by Django 5.2 on 2025-04-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trailer_url', models.URLField()),
                ('movie_url', models.URLField()),
                ('poster', models.ImageField(upload_to='films/')),
                ('genre', models.CharField(max_length=100)),
                ('background_class', models.CharField(max_length=100)),
            ],
        ),
    ]
