# Generated by Django 5.2 on 2025-04-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='background_class',
        ),
        migrations.AddField(
            model_name='movie',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
